name: Upload coverage on push
on:
  push:
    branches: ['main']
jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: corepack enable
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
      - run: yarn install --immutable
      - run: yarn test
      - uses: codecov/codecov-action@v7
        with:
          files: './coverage.lcov,./coverage.xml'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
